include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - require_trailing_commas

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
