name: todo_firebase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  freezed: ^2.5.2
  freezed_annotation: any
  logging: ^1.2.0
  shared_preferences: ^2.2.3

  #serialization
  json_serializable: ^6.8.0

  #slivers
  flutter_sticky_header: ^0.6.5

  #firebase
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0

  #intl
  intl: ^0.19.0

  #routing
  auto_route: ^8.2.0

  #test
  bloc_test: ^9.1.7
  mocktail:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
