// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nlsj1X4PkVNbiVSqm0KMOojhkw-liUY',
    appId: '1:467550608061:web:1ba9d383fd20f9351375d4',
    messagingSenderId: '467550608061',
    projectId: 'todo-firebase-2ccbf',
    authDomain: 'todo-firebase-2ccbf.firebaseapp.com',
    storageBucket: 'todo-firebase-2ccbf.appspot.com',
    measurementId: 'G-8LCEN7QHCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJBHZKeutu2LDCB0es8C9rfpNiWqxBAc',
    appId: '1:467550608061:android:89f4d02762a09a741375d4',
    messagingSenderId: '467550608061',
    projectId: 'todo-firebase-2ccbf',
    storageBucket: 'todo-firebase-2ccbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1hwVwyE8VYrHJpZGn8zBoFn2XoCsAgQ',
    appId: '1:467550608061:ios:8016d92d4d0af3251375d4',
    messagingSenderId: '467550608061',
    projectId: 'todo-firebase-2ccbf',
    storageBucket: 'todo-firebase-2ccbf.appspot.com',
    iosBundleId: 'com.animousen4.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1hwVwyE8VYrHJpZGn8zBoFn2XoCsAgQ',
    appId: '1:467550608061:ios:8016d92d4d0af3251375d4',
    messagingSenderId: '467550608061',
    projectId: 'todo-firebase-2ccbf',
    storageBucket: 'todo-firebase-2ccbf.appspot.com',
    iosBundleId: 'com.animousen4.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_nlsj1X4PkVNbiVSqm0KMOojhkw-liUY',
    appId: '1:467550608061:web:ff1f3e8f7632ca901375d4',
    messagingSenderId: '467550608061',
    projectId: 'todo-firebase-2ccbf',
    authDomain: 'todo-firebase-2ccbf.firebaseapp.com',
    storageBucket: 'todo-firebase-2ccbf.appspot.com',
    measurementId: 'G-462KMPW8TZ',
  );

}